### ISSUE TITLE
IDPPublic war fails to launch in idp plays (SAGrid)

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#158]
The error returned in the catalina log is : 

```
Jan 16, 2015 4:35:10 PM org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
SEVERE: A web application created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal] (value [Prototype beans currently in creation]) and a value of type [null] (value [null]) but failed to remove it when the web application was stopped. To prevent a memory leak, the ThreadLocal has been forcibly removed.
Exception in thread "HSQLDB Timer @741d5c7d" java.lang.NullPointerException
	at org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
	at org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Jan 16, 2015 4:35:10 PM org.apache.coyote.http11.Http11Protocol destroy
```

symptoms : 

  * tomcat is started, but http is not responding.

**Comment by brucellino** [comment]
http://shibboleth.net/pipermail/users/2011-November/001801.html references the issue and suggests that the wrong xerces jar is being loaded. This might have to do with the the endorsed directories not being set properly.

**Comment by brucellino** [comment]
Some more info : 

```
ps aux | grep java
tomcat    7401 31.8  8.0 3017236 317472 ?      Sl   16:57   0:39 /usr/lib/jvm/java/bin/java -Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory -Xmx512m -XX:MaxPermSize=128m -classpath :/usr/share/tomcat6/bin/bootstrap.jar:/usr/share/tomcat6/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/usr/share/tomcat6 -Dcatalina.home=/usr/share/tomcat6 -Djava.endorsed.dirs=/usr/share/tomcat6/lib/endorsed -Djava.io.tmpdir=/var/cache/tomcat6/temp -Djava.util.logging.config.file=/usr/share/tomcat6/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
root      7468  0.0  0.0 103248   840 pts/0    S+   17:00   0:00 grep java
[root@idp ~]# netstat -tan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State      
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      
tcp        0     48 196.21.182.116:22           193.206.208.201:40247       ESTABLISHED 
tcp        0    840 196.21.182.116:22           103.41.124.54:45470         ESTABLISHED 
tcp        0      0 :::22                       :::*                        LISTEN      
tcp        0      0 ::1:25                      :::*                        LISTEN      
tcp        0      0 :::8443                     :::*                        LISTEN      
tcp        0      0 ::ffff:127.0.0.1:8005       :::*                        LISTEN      
tcp        0      0 :::8009                     :::*                        LISTEN      
tcp        0      0 :::8080                     :::*                        LISTEN      
tcp        0      0 ::ffff:196.21.182.116:44532 ::ffff:196.21.182.114:389   ESTABLISHED 
tcp        0      0 ::ffff:196.21.182.116:44528 ::ffff:196.21.182.114:389   ESTABLISHED 
[root@idp ~]# 
```

**Comment by brucellino** [comment]
The issue has been identified - the old version of the library  was present from a previous install. This meant that the file copy was skipped. Cleaning out the old install and re-running the playbook fixed the problem.
