### ISSUE TITLE
Error in configuration of SAGrid database for science gateway

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#179]
The current configuration (cd85e153a91b6d76c70fa8fd9abe75c2be7810ba) is incorrectly setting the database connectin parameters in the db for the science gateway. In the liferay domain logs, we get: 

```
19:01:02,736 ERROR [http-thread-pool-8009(2)][UsersTrackingDBInterface:148] Cannot get connection: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Access denied for user 'tracking_user'@'science-gateway.sagrid.ac.za' (using password: YES)
19:01:02,739 INFO  [http-thread-pool-8009(2)][UsersTrackingDBInterface:697] Cannot get active jobs list from DB: DB Connection is closed.
19:01:02,748 ERROR [http-thread-pool-8009(2)][render_portlet_jsp:154] java.lang.NullPointerException
	at it.infn.ct.GridEngine.UsersTracking.UsersTrackingDBInterface.getActiveInteractionsByName(UsersTrackingDBInterface.java:578)
	at it.infn.ct.MyJobs.MyJobs.doView(MyJobs.java:95)
```

**Comment by brucellino** [comment]
The DB user creation seems to have gone ok : 
```
ok: [db.sagrid.ac.za] => (item=[{'pass': 'userstracking', 'name': 'tracking_user', 'priv': 'userstracking.*:ALL'}, 'science-gateway.sagrid.ac.za'])
ok: [db.sagrid.ac.za] => (item=[{'pass': 'liferayadmindbpass', 'name': 'liferayadmin', 'priv': 'lportal.*:ALL'}, 'science-gateway.sagrid.ac.za'])
```
Checking these by hand also seems to work fine : 
```
[root@science-gateway ~]# mysql -h db.sagrid.ac.za -u tracking_user -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 135
Server version: 5.1.73 Source distribution

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

**Comment by brucellino** [comment]
ok. removing the domain and the connector jars, re-running the playbook, I managed to work around this. Not sure why.
