### ISSUE TITLE
problem with hibernate in SAGrid IdP 

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#181]
When restarting the tomcat6 service, we see

```
INFO: Stopping Coyote HTTP/1.1 on http-8443
Exception in thread "HSQLDB Timer @7ce474af" java.lang.NullPointerException
	at org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
	at org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
in the catalina.out log.

**Comment by brucellino** [comment]
Haven't been able to reproduce this so closing it.
