### ISSUE TITLE
tomcat error arising when executing playbook -

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#182]
```
INFO: Undeploying context []
Feb 11, 2015 1:07:02 PM org.apache.catalina.startup.HostConfig checkResources
WARNING: Error while removing context []
java.lang.NoClassDefFoundError: org/apache/struts2/util/ObjectFactoryDestroyable
	at org.apache.struts2.dispatcher.Dispatcher.cleanup(Dispatcher.java:265)
	at org.apache.struts2.dispatcher.ng.PrepareOperations.cleanupDispatcher(PrepareOperations.java:179)
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.destroy(StrutsPrepareAndExecuteFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:357)
	at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4111)
	at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4880)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:924)
	at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1174)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1342)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1337)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1601)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1610)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.struts2.util.ObjectFactoryDestroyable
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1483)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1329)
	... 16 more
```

**Comment by fmarco76** [comment]
When did you get this error (startup. shutdown or randomly during normal execution)?

**Comment by brucellino** [comment]
at shutdown.

**Comment by fmarco76** [comment]
Googleing this error it seems the problem is with the order the classloader discard the class. It remove the class before the use. There are several solution proposed but they are based on trial and error changing the order how the libraries are loaded. I should find the time for some tests

**Comment by fmarco76** [comment]
However, since is is at shutdown there is not problem with the running service and even the stop is not clean there are not inconsistent states. So it is safe to execute in any case

**Comment by brucellino** [comment]
Ok. Closing this then.
