### ISSUE TITLE
Issue starting tomcat in idp play

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#289]
We are getting the following error in the catalina log when running the `idp-ldap.yml` playbook : 

```
SEVERE: Error starting static Resources
java.lang.IllegalArgumentException: Document base /usr/share/tomcat6/webapps/ROOT does not exist or is not a readable directory
	at org.apache.naming.resources.FileDirContext.setDocBase(FileDirContext.java:142)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4324)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4493)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:526)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:722)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
	at org.apache.catalina.core.StandardService.start(StandardService.java:516)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:593)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

Feb 03, 2016 7:37:56 PM org.apache.catalina.core.StandardContext start
SEVERE: Error in resourceStart()
Feb 03, 2016 7:37:56 PM org.apache.catalina.core.StandardContext start
SEVERE: Error getConfigured
Feb 03, 2016 7:37:56 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [] startup failed due to previous errors
Feb 03, 2016 7:37:56 PM org.apache.catalina.core.StandardContext stop
INFO: Container org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/] has not been started
```

The directory is indeed not there, but the war is : 

```
s -lht /usr/share/tomcat6/webapps/
total 12M
-rw-r--r-- 1 tomcat tomcat  12M Feb  3 19:36 ROOT.war
drw-r--r-- 2 tomcat tomcat 4.0K Feb  3 19:36 ROOT.old
```
The question then is why is the war not being autodeployed ?

**Comment by brucellino** [comment]
this was a permissions issue on the `webapps` directory.

**Comment by brucellino** [comment]
can't reproduce.
