### ISSUE TITLE
TERNET IDP Cant login

### ISSUE THREAD

**Issue by dmakweba** [AAROC/DevOps#333]
#  Issue type

TERNET IDP is having problem whereby we cant be able to login directly at https://idp.ternet.or.tz neither at other federated services like SG. The error type I found at the logs is about certificate as described below; unable to find valid certificate.....
```
at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: **unable to find valid certification path to requested target**
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
```

How would you best describe your issue  ?

  - [ ] Ansible problem
  - [ ] Puppet problem
  - [ ] Container problem
  - [ ] Want to join as collaborator
  - [x] General question, enhancement or suggestion

Please suggest a tag to the issue from the list provided, if relevant.

# Issue description

Unfortunately this IDP was the first deployment when we did manual installation, neither of automation tool used.
Any assistant please.

**Comment by brucellino** [comment]
Hi @dmakweba  thanks for reporting the issue. I've  updated the issue temmplate, since some info was missing in your submission. I'm going to close this and ask you to open a new one please.

Thanks ! 
Bruce
