### ISSUE TITLE
ZeroMQ dependency error on Undercloud install

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#381]
#  Issue type

OS package dependency error

# Repository information

  * Branch: master
  * git hash: a7a636db158

# Issue description

Running `openstack undercloud install` on the ZA-UJ undercloud failed with a yum dependency error

# Logs and other information

```
2017-11-22 15:31:33,505 INFO: --> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-2.el7.x86_64
2017-11-22 15:31:50,089 INFO: --> Finished Dependency Resolution
2017-11-22 15:31:50,308 INFO: Error: Package: python-zmq-14.7.0-2.el7.x86_64 (@delorean-newton-testing)
2017-11-22 15:31:50,310 INFO:            Requires: libzmq.so.4()(64bit)
2017-11-22 15:31:50,312 INFO:            Removing: zeromq-4.0.5-4.el7.x86_64 (@delorean-newton-testing)
2017-11-22 15:31:50,314 INFO:                libzmq.so.4()(64bit)
2017-11-22 15:31:50,316 INFO:            Updated By: zeromq-4.1.4-5.el7.x86_64 (epel)
2017-11-22 15:31:50,317 INFO:               ~libzmq.so.5()(64bit)
2017-11-22 15:31:50,319 INFO:  You could try using --skip-broken to work around the problem
2017-11-22 15:31:54,250 INFO:  You could try running: rpm -Va --nofiles --nodigest
2017-11-22 15:31:54,625 DEBUG: An exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 1802, in install
    _run_yum_update(instack_env)
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 1318, in _run_yum_update
    _run_live_command(args, instack_env, 'yum-update')
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 601, in _run_live_command
    raise RuntimeError('%s failed. See log for details.' % name)
RuntimeError: yum-update failed. See log for details.
```

**Comment by brucellino** [comment]
There were `delorean` and `rdo` yum repos - I removed the delorean ones, let's see what happens.

**Comment by brucellino** [comment]
Fixed by : 

  1. removing delorean repos
  1. cleaning yum 
  1. update and upgrading everything
  1. add pike repos
  1. re-run `openstack undercloud install`
